### PR TITLE
need only 1 http request

### PR DESCRIPTION
**Pull request by tomByrer**
https://github.com/jsdelivr/jsdelivr#load-multiple-files-with-single-http-request

### CODE REVIEW

**Comment by jimaek** [comment]
I dont think it will work in this case. fontawesome loads more files inside the CSS. Those files will fail to load when using /g/ because of the wrong relative paths.

**Comment by tomByrer** [comment]
If that's the case, then we should put a warning in the instructions against this practice.

Let me or someone test this out; I have collated JS files that had other resources as well (PNG files for icons).  I didn't get any errors & everything seems ok.

**Comment by jimaek** [comment]
Non /g/ http://codepen.io/anon/pen/jWBzPd
/g/ http://codepen.io/anon/pen/XXMEbJ

It breaks because the HTTP requests go to the wrong path.

**Comment by kernc** [comment]
Both worked for me, but then I remembered I had FontAwesome locally installed. So combining appears to not work with resources that load additional resources with a relative path. There's really no way around it, unless jsDeliver starts patching them files, which would be far more trouble than it is worth. Thanks, though.

**Comment by jimaek** [comment]
No way they are both working for you. https://dl.dropboxusercontent.com/s/zul5hp8e45fexuv/2016-01-06_15-51-25.png?dl=0

**Comment by kernc** [comment]
> but then I remembered I had FontAwesome locally installed.

As in `apt-get install fonts-font-awesome`; as in its `*.otf` copied into `~/.fonts` . :smile:

**Comment by jimaek** [comment]
Oh I see :)

**Pull request closed without merging**
